export type BookingCategory = "景點" | "交通" | "活動／服務" | "住宿";
export type BookingPriority = "已預訂" | "最優先" | "建議預約" | "等候開賣" | "不用預約";

export interface BookingItem {
  date: string;
  itinerary: string;
  category: BookingCategory;
  item: string;
  saleStart: string;
  action: string;
  slot: string;
  priority: BookingPriority;
  note: string;
  url: string;
  linkLabel: string;
}

export const BOOKING_ITEMS: BookingItem[] = [
  {
    date: "10/22（四）",
    itinerary: "抵達後轉往 Madrid",
    category: "交通",
    item: "Barcelona Sants → Madrid Atocha 高速列車",
    saleStart: "Renfe 一般最長約提前 12 個月，但實際班次會分批載入",
    action: "現在查票；鎖定行李與入境緩衝後再買",
    slot: "17:25 之後直達班次",
    priority: "最優先",
    note: "BCN 機場到 Sants 不需預約；航班誤點風險高，宜買可改票價。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/23（五）",
    itinerary: "Madrid 藝術日",
    category: "景點",
    item: "Museo del Prado 普拉多美術館",
    saleStart: "已完成訂票：2 位成人・實付 NT$1,322",
    action: "訂單已確認；出發前下載並離線保存憑證",
    slot: "10:00 開館入場",
    priority: "已預訂",
    note: "10:00 指定時段入場；憑證條碼與訂單編號僅保留在私人裝置。",
    url: "https://entradas.museodelprado.es/",
    linkLabel: "Prado 官方票務",
  },
  {
    date: "10/23（五）",
    itinerary: "Madrid 藝術與王室日",
    category: "景點",
    item: "Palacio Real de Madrid 馬德里皇宮",
    saleStart: "已完成訂票：Palace＋Gallery Visit・2 位成人",
    action: "出發前下載票券與手機語音導覽；訂單編號僅保留在私人裝置",
    slot: "15:30 皇宮入場",
    priority: "已預訂",
    note: "總額 €52.54（標準票 €48、語音導覽 €3、手續費 €1.54）。皇宮預留約 1.5–2 小時；皇家收藏館可在皇宮參觀日起 7 天內另行使用。官方活動可能臨時造成部分關閉，請於 15:15 前抵達。",
    url: "https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid",
    linkLabel: "皇宮官方票務",
  },
  {
    date: "10/24（六）",
    itinerary: "Madrid 足球日",
    category: "活動／服務",
    item: "Atlético Madrid vs RC Deportivo",
    saleStart: "已完成購票：Lateral Oeste Grada Alta・€50",
    action: "比賽時間已由 Atlético 與 LaLiga 官方確認；出發前下載票券並再次查看公告",
    slot: "21:00 開球；建議 19:00–19:30 抵達球場",
    priority: "已預訂",
    note: "Riyadh Air Metropolitano 主場。18:15–18:30 左右從市中心出發，預留安檢、找入口與座位時間；票券編號、姓名、完整座位與入場憑證僅保留在私人票券中。",
    url: "https://en.atleticodemadrid.com/tickets/",
    linkLabel: "Atlético 官方票務",
  },
  {
    date: "10/22–26",
    itinerary: "Madrid 住宿基地",
    category: "住宿",
    item: "Piso elegante Atocha 2H/2B by Berlany España",
    saleStart: "已完成預訂：2 位成人、1 間公寓、4 晚",
    action: "抵達前 24 小時留意手機上的自助入住連結",
    slot: "10/22 15:00 後入住・10/26 11:00 前退房",
    priority: "已預訂",
    note: "地址：Calle de Atocha 94, 28012 Madrid。使用門碼自助入住，不需下載 App；門碼不要放在公開頁面。",
    url: "#hotels",
    linkLabel: "查看飯店建議",
  },
  {
    date: "10/26（一）",
    itinerary: "Madrid → Sevilla",
    category: "交通",
    item: "Madrid Atocha → Sevilla Santa Justa",
    saleStart: "已完成訂票：Renfe AVE 02100・Choice-Comfort",
    action: "出發當日查看月台，並提早約 30 分鐘抵達車站",
    slot: "10:00 Madrid Puerta de Atocha → 12:40 Sevilla Santa Justa",
    priority: "已預訂",
    note: "車程 2 小時 40 分；抵達後先到飯店寄放行李。PNR、QR code、姓名與完整座位資料不放在公開網站。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/26–28",
    itinerary: "Sevilla 住宿基地",
    category: "住宿",
    item: "Hotel Rey Alfonso X・住宿人數待更正",
    saleStart: "已完成預訂：實際為 2 位成人；訂單誤列 1 位兒童與加床",
    action: "10/25 前確認行程；免費取消期限至 10/25",
    slot: "10/26 16:00 起入住・10/28 12:00 前退房",
    priority: "已預訂",
    note: "Autumn Promotion、Room Only，含 Wi-Fi；總價 €457.60。飯店現場付款，信用卡僅作預訂擔保。地址：Ximénez de Enciso 35, 41004 Sevilla。",
    url: "https://www.hotelreyalfonsox.es/en/",
    linkLabel: "Hotel Rey Alfonso X 官網",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 完整觀光日",
    category: "景點",
    item: "Real Alcázar de Sevilla",
    saleStart: "已完成訂票：2 位成人・實付 NT$1,542",
    action: "訂單已確認；出發前下載並離線保存憑證",
    slot: "09:30 入場",
    priority: "已預訂",
    note: "09:30 指定時段入場；王宮與花園預留約 2.5 小時。憑證條碼與訂單編號不要公開。",
    url: "https://tickets.alcazarsevilla.org/",
    linkLabel: "Alcázar 官方票務",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 完整觀光日",
    category: "景點",
    item: "Sevilla Cathedral＋Giralda",
    saleStart: "已完成訂票：2 位成人・實付 NT$1,322",
    action: "訂單已確認；出發前下載並離線保存憑證",
    slot: "14:30 入場",
    priority: "已預訂",
    note: "14:30 指定時段入場；憑證條碼與訂單編號僅保留在私人裝置。教堂宗教活動可能調整開放時間。",
    url: "https://catedraldesevilla.entradasdemuseos.com/",
    linkLabel: "大教堂官方票務",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 夜間活動",
    category: "活動／服務",
    item: "Santa Cruz／Triana 佛朗明哥表演",
    saleStart: "多數場館已可預約數月後場次，各館不同",
    action: "Alcázar 與教堂時段確定後再訂",
    slot: "20:00 或 21:00",
    priority: "建議預約",
    note: "選純表演或飲品方案即可；不必綁晚餐，保留餐廳彈性。",
    url: "https://www.casadelamemoria.es/en/",
    linkLabel: "場館範例／官方",
  },
  {
    date: "10/28（三）",
    itinerary: "Sevilla → Granada",
    category: "交通",
    item: "Sevilla Santa Justa → Granada Avant",
    saleStart: "已完成訂票：Renfe Avant 08295・二等車廂",
    action: "出發當日查看月台，並提早約 30 分鐘抵達車站",
    slot: "09:55 Sevilla Santa Justa → 12:35 Granada",
    priority: "已預訂",
    note: "車程 2 小時 40 分；抵達後先寄放行李並午餐，再前往 Albaicín。PNR、QR code、姓名與完整座位資料不放在公開網站。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/28–30",
    itinerary: "Granada 住宿基地",
    category: "住宿",
    item: "Hotel Room Mate Leo・Deluxe room",
    saleStart: "已完成預訂：2 位成人、1 間客房、2 晚",
    action: "10/21 前確認行程；免費取消期限至 10/21",
    slot: "10/28 15:00 起入住・10/30 12:00 前退房",
    priority: "已預訂",
    note: "含兩日自助早餐；Special Web Rate Semi Flexible，總價 €391.88（含稅後頁面總額）。地址：Campo Verde 1, 18001 Granada。",
    url: "https://room-matehotels.com/en/leo/",
    linkLabel: "Room Mate Leo 官網",
  },
  {
    date: "10/29（四）",
    itinerary: "Granada 核心日",
    category: "景點",
    item: "Alhambra General＋Nasrid Palaces",
    saleStart: "已完成預訂：Alhambra General Visit 成人票",
    action: "當天 08:30 前抵達園區，08:40 前到 Nasrid Palaces 入口",
    slot: "Nasrid Palaces 09:00",
    priority: "已預訂",
    note: "票價 €21＋€1.27 手續費，共 €22.27。攜帶購票所用護照正本；QR code、預約號、訂單號及證件資料保留在私人裝置。",
    url: "https://tickets.alhambra-patronato.es/en/producto/alhambra-general/",
    linkLabel: "Alhambra 官方票務",
  },
  {
    date: "10/29（四）",
    itinerary: "Granada 核心日",
    category: "交通",
    item: "Centro → Alhambra 市區公車／計程車",
    saleStart: "不需預約；公車現場刷票／購票",
    action: "當天約 07:45 從 Room Mate Leo 出發",
    slot: "預留 30–40 分鐘",
    priority: "不用預約",
    note: "目標 08:15–08:25 抵達園區；Alhambra 很大，不要把抵達園區時間當成 Nasrid 入口時間。",
    url: "https://www.alhambra-patronato.es/en/visit/how-to-get-there",
    linkLabel: "官方交通說明",
  },
  {
    date: "10/30（五）",
    itinerary: "Granada → Barcelona",
    category: "交通",
    item: "Vueling GRX → BCN 直飛",
    saleStart: "已完成訂票：Vueling VY1105 直飛",
    action: "前一晚確認托運行李、登機證、機場接送與外帶早餐",
    slot: "09:05 Granada GRX → 10:30 Barcelona BCN",
    priority: "已預訂",
    note: "航程 1 小時 25 分；建議約 06:45–06:55 從 Room Mate Leo 出發，最晚約 07:35 抵達機場。訂位代碼與登機證不放在公開網站。",
    url: "https://www.vueling.com/en/flights-from-granada-to-barcelona",
    linkLabel: "Vueling 官網",
  },
  {
    date: "10/30–11/1",
    itinerary: "Barcelona 住宿基地",
    category: "住宿",
    item: "NH Collection Barcelona Gran Hotel Calderón",
    saleStart: "已完成預訂：五星飯店、連住 2 晚",
    action: "出發前從 Booking.com 訂單頁再次確認房型、價格與取消條款",
    slot: "10/30 15:00 起入住・11/1 12:00 前退房",
    priority: "已預訂",
    note: "地址：Rambla de Catalunya 26, Eixample, 08007 Barcelona。截圖未顯示房型、人數、價格與取消期限，待完整確認單補充。",
    url: "https://www.nh-collection.com/en/hotel/nh-collection-barcelona-gran-hotel-calderon",
    linkLabel: "NH Collection 官網",
  },
  {
    date: "10/31（六）",
    itinerary: "Barcelona 核心日",
    category: "景點",
    item: "Sagrada Família 聖家堂",
    saleStart: "已完成預訂：General（€36）＋Audioguide＋Passion Tower",
    action: "當天 08:30 前抵達，預留安檢與驗票時間",
    slot: "09:00 入場・09:15 Passion Tower",
    priority: "已預訂",
    note: "票券僅限指定時段；塔樓可能因天候臨時關閉。QR code、預約號與票號請保留在私人裝置。",
    url: "https://sagradafamilia.org/en/tickets",
    linkLabel: "聖家堂官方票務",
  },
];

export const BOOKING_SOURCES = [
  { label: "Renfe：一般預售規則", url: "https://www.renfe.com/es/es/normativa" },
  { label: "馬德里皇宮：90 天規則", url: "https://tickets.patrimonionacional.es/es/preguntas-frecuentes" },
  { label: "Alhambra：官方售票", url: "https://tickets.alhambra-patronato.es/en/" },
  { label: "聖家堂：約提前兩個月", url: "https://sagradafamilia.org/en/faqs" },
];
