export type BookingCategory = "景點" | "交通" | "活動／服務" | "住宿";
export type BookingPriority = "已預訂" | "最優先" | "建議預約" | "等候開賣" | "不用預約";

export interface BookingItem {
  date: string;
  itinerary: string;
  category: BookingCategory;
  item: string;
  saleStart: string;
  action: string;
  slot: string;
  priority: BookingPriority;
  note: string;
  url: string;
  linkLabel: string;
}

export const BOOKING_ITEMS: BookingItem[] = [
  {
    date: "10/22（四）",
    itinerary: "抵達後轉往 Madrid",
    category: "交通",
    item: "Barcelona Sants → Madrid Atocha 高速列車",
    saleStart: "Renfe 一般最長約提前 12 個月，但實際班次會分批載入",
    action: "現在查票；鎖定行李與入境緩衝後再買",
    slot: "17:25 之後直達班次",
    priority: "最優先",
    note: "BCN 機場到 Sants 不需預約；航班誤點風險高，宜買可改票價。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/23（五）",
    itinerary: "Madrid 藝術日",
    category: "景點",
    item: "Museo del Prado 普拉多美術館",
    saleStart: "官網採日期／時段票，未公告固定的統一放票日",
    action: "10 月日曆出現後立即購買；現在開始每週查看",
    slot: "10:00 開館入場",
    priority: "建議預約",
    note: "一般票含常設與當期特展；免費時段排隊長，不適合本行程。",
    url: "https://entradas.museodelprado.es/",
    linkLabel: "Prado 官方票務",
  },
  {
    date: "10/24（六）",
    itinerary: "Madrid 王室日",
    category: "景點",
    item: "Palacio Real de Madrid 馬德里皇宮",
    saleStart: "最多提前 90 天；10/24 約自 7/26 開放",
    action: "已進入售票窗，現在購買",
    slot: "10:00 首批時段",
    priority: "最優先",
    note: "官方活動可能臨時造成部分關閉；入場前 15 分鐘抵達。",
    url: "https://tickets.patrimonionacional.es/en/tickets/palacio-real-de-madrid",
    linkLabel: "皇宮官方票務",
  },
  {
    date: "10/24–25",
    itinerary: "Madrid 足球彈性日",
    category: "活動／服務",
    item: "Atlético Madrid vs RC Deportivo",
    saleStart: "確切日程與開球時間確認後，由俱樂部分階段開賣；無固定提前天數",
    action: "現在登記 Avísame；收到通知再從官方購票",
    slot: "兩天保持可互換",
    priority: "等候開賣",
    note: "不要先買非官方轉售票；比賽日確定前，10/24–25 的定時景點要保留彈性。",
    url: "https://en.atleticodemadrid.com/tickets/",
    linkLabel: "Atlético 官方票務",
  },
  {
    date: "10/22–26",
    itinerary: "Madrid 住宿基地",
    category: "住宿",
    item: "Piso elegante Atocha 2H/2B by Berlany España",
    saleStart: "已完成預訂：2 位成人、1 間公寓、4 晚",
    action: "抵達前 24 小時留意手機上的自助入住連結",
    slot: "10/22 15:00 後入住・10/26 11:00 前退房",
    priority: "已預訂",
    note: "地址：Calle de Atocha 94, 28012 Madrid。使用門碼自助入住，不需下載 App；門碼不要放在公開頁面。",
    url: "#hotels",
    linkLabel: "查看飯店建議",
  },
  {
    date: "10/26（一）",
    itinerary: "Madrid → Sevilla",
    category: "交通",
    item: "Madrid Atocha → Sevilla Santa Justa",
    saleStart: "Renfe 一般最長約提前 12 個月；班表可能因工程分批開放",
    action: "現在查 Renfe／iryo，有合適直達班次即購買",
    slot: "10:00–13:00 出發",
    priority: "最優先",
    note: "若球賽排 10/25 晚場，選 10/26 中午前後班次；約 2 小時 40 分。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 完整觀光日",
    category: "景點",
    item: "Real Alcázar de Sevilla",
    saleStart: "官方日曆滾動開放，沒有保證的固定放票日",
    action: "現在查看 10/27；一開放立即買",
    slot: "09:30 入場",
    priority: "最優先",
    note: "只使用官方售票頁；王宮與花園預留約 2.5 小時。",
    url: "https://tickets.alcazarsevilla.org/",
    linkLabel: "Alcázar 官方票務",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 完整觀光日",
    category: "景點",
    item: "Sevilla Cathedral＋Giralda",
    saleStart: "官方日曆滾動開放，未公布固定提前天數",
    action: "與 Alcázar 同日確認後購買",
    slot: "14:00 入場",
    priority: "建議預約",
    note: "線上票可走預約入口；教堂宗教活動可能調整開放時間。",
    url: "https://catedraldesevilla.entradasdemuseos.com/",
    linkLabel: "大教堂官方票務",
  },
  {
    date: "10/27（二）",
    itinerary: "Sevilla 夜間活動",
    category: "活動／服務",
    item: "Santa Cruz／Triana 佛朗明哥表演",
    saleStart: "多數場館已可預約數月後場次，各館不同",
    action: "Alcázar 與教堂時段確定後再訂",
    slot: "20:00 或 21:00",
    priority: "建議預約",
    note: "選純表演或飲品方案即可；不必綁晚餐，保留餐廳彈性。",
    url: "https://www.casadelamemoria.es/en/",
    linkLabel: "場館範例／官方",
  },
  {
    date: "10/28（三）",
    itinerary: "Sevilla → Granada",
    category: "交通",
    item: "Sevilla Santa Justa → Granada Avant",
    saleStart: "Renfe 一般最長約提前 12 個月；Avant 班表可能較晚載入",
    action: "現在查票；若尚未載入則每週重查",
    slot: "07:14 起的上午直達班次",
    priority: "最優先",
    note: "約 2 小時 30 分；早到 Granada 才能保留 Albaicín 下午行程。",
    url: "https://www.renfe.com/es/en",
    linkLabel: "Renfe 官網",
  },
  {
    date: "10/28–30",
    itinerary: "Granada 住宿基地",
    category: "住宿",
    item: "Hotel Room Mate Leo・Deluxe room",
    saleStart: "已完成預訂：2 位成人、1 間客房、2 晚",
    action: "10/21 前確認行程；免費取消期限至 10/21",
    slot: "10/28 15:00 起入住・10/30 12:00 前退房",
    priority: "已預訂",
    note: "含兩日自助早餐；Special Web Rate Semi Flexible，總價 €391.88（含稅後頁面總額）。地址：Campo Verde 1, 18001 Granada。",
    url: "https://room-matehotels.com/en/leo/",
    linkLabel: "Room Mate Leo 官網",
  },
  {
    date: "10/29（四）",
    itinerary: "Granada 核心日",
    category: "景點",
    item: "Alhambra General＋Nasrid Palaces",
    saleStart: "最長約提前 12 個月，並依長／中／短期配額分批釋出",
    action: "已開賣，現在立即購買",
    slot: "Nasrid Palaces 10:00",
    priority: "最優先",
    note: "票面時間是 Nasrid 入場時間；09:40 前到入口，攜帶購票所用護照正本。",
    url: "https://tickets.alhambra-patronato.es/en/producto/alhambra-general/",
    linkLabel: "Alhambra 官方票務",
  },
  {
    date: "10/29（四）",
    itinerary: "Granada 核心日",
    category: "交通",
    item: "Centro → Alhambra 市區公車／計程車",
    saleStart: "不需預約；公車現場刷票／購票",
    action: "當天 08:30 前從 Centro 出發",
    slot: "預留 30–40 分鐘",
    priority: "不用預約",
    note: "Alhambra 園區很大；不要把抵達園區時間當成 Nasrid 入口時間。",
    url: "https://www.alhambra-patronato.es/en/visit/how-to-get-there",
    linkLabel: "官方交通說明",
  },
  {
    date: "10/30（五）",
    itinerary: "Granada → Barcelona",
    category: "交通",
    item: "Vueling GRX → BCN 直飛",
    saleStart: "航班已進入銷售期，航空公司採浮動票價",
    action: "現在購買，並一次加好托運行李",
    slot: "優先上午直飛",
    priority: "最優先",
    note: "比較含行李總價，不要只看 Basic 裸票；抵達日不綁定景點門票。",
    url: "https://www.vueling.com/en/flights-from-granada-to-barcelona",
    linkLabel: "Vueling 官網",
  },
  {
    date: "10/31（六）",
    itinerary: "Barcelona 核心日",
    category: "景點",
    item: "Sagrada Família 聖家堂",
    saleStart: "官方約提前 2 個月；10/31 約自 8/31 前後開始留意",
    action: "8/25 起每日查看，開放 10/31 就購買",
    slot: "09:30 入場；登塔依供給",
    priority: "等候開賣",
    note: "遲到不能入場；若選塔樓，電梯上行、步行下樓，天候可能臨時關閉。",
    url: "https://sagradafamilia.org/en/tickets",
    linkLabel: "聖家堂官方票務",
  },
];

export const BOOKING_SOURCES = [
  { label: "Renfe：一般預售規則", url: "https://www.renfe.com/es/es/normativa" },
  { label: "馬德里皇宮：90 天規則", url: "https://tickets.patrimonionacional.es/es/preguntas-frecuentes" },
  { label: "Alhambra：官方售票", url: "https://tickets.alhambra-patronato.es/en/" },
  { label: "聖家堂：約提前兩個月", url: "https://sagradafamilia.org/en/faqs" },
];
